/**:
  ros__parameters:
    gait:
      knee_orientation : ">>"
      pantograph_leg : false
      odom_scaler: 0.1
      max_linear_velocity_x : 0.8
      max_linear_velocity_y : 0.50
      max_angular_velocity_z : 1.0
      com_x_translation: 0.0
      swing_height : 0.04
      stance_depth : 0.00
      stance_duration : 0.40
      nominal_height : 0.4
    loop_rate: 50.0  
    use_sim_time: true
    base: base_link
    left_front: ["front_left_hip","front_left_upper_leg","front_left_lower_leg","front_left_ee"]
    right_front: ["front_right_hip","front_right_upper_leg","front_right_lower_leg","front_right_ee"]
    left_hind: ["rear_left_hip","rear_left_upper_leg","rear_left_lower_leg","rear_left_ee"]
    right_hind: ["rear_right_hip","rear_right_upper_leg","rear_right_lower_leg","rear_right_ee"]