base_to_footprint_ekf:
  ros__parameters:
    use_sim_time: true
    clear_params: true
    publish_tf: true
    filter_type: "ekf"
    frequency: 50.0
    sensor_timeout: 0.05
    pose0: base_to_footprint_pose
    imu0: imu/data
    odom_frame: base_footprint
    world_frame: base_footprint
    pose0_config: [true, true, true,
                  true,  true,  true, # roll , pitch ,yaw
                  false, false, false,  # dX , dY , dZ
                  false, false, false, # droll , dpitch ,dyaw
                  false, false, false] # ddX , ddY , ddZ

    imu0_config: [false,  false, false,  # X , Y , Z
                  false,  false, false,  # roll , pitch ,yaw
                  true,   true,   true,  # dX , dY , dZ
                  false,  false,  false,  # droll , dpitch ,dyaw
                  false,  false,  false] # ddX , ddY , ddZ
    imu0_relative: false                
    imu0_differential: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

footprint_to_odom_ekf:
  ros__parameters:
    use_sim_time: true
    clear_params: true
    publish_tf: true
    filter_type: "ekf"
    frequency: 50.0
    sensor_timeout: 0.05
    odom0: odom/raw
    imu0: imu/data
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom
    odom0_config: [false,  false, false, # X , Y , Z
                    false, false, false,  # roll , pitch ,yaw
                    true, true, false,     # dX , dY , dZ
                    false, false, true,   # droll , dpitch ,dyaw
                    false, false, false]  # ddX , ddY , ddZ
    odom0_relative: false
    odom0_differential: false
    odom0_queue_size: 10
    imu0_config: [false,  false, false, # X , Y , Z
                  false,  false, true,  # roll , pitch ,yaw
                  false,  false, false, # dX , dY , dZ
                  false,  false, true, # droll , dpitch ,dyaw
                  false,  false, false] # ddX , ddY , ddZ
    imu0_relative: false
    imu0_differential: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true
