controller_manager:
  ros__parameters:
    update_rate: 200
    publish_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 200

joint_trajectory_controller:   
  ros__parameters:
    state_publish_rate: 200.0
    action_monitor_rate: 200.0
    joints:
        - lf_hip_joint
        - lf_upper_leg_joint
        - lf_lower_leg_joint
        - rf_hip_joint
        - rf_upper_leg_joint
        - rf_lower_leg_joint
        - lh_hip_joint
        - lh_upper_leg_joint
        - lh_lower_leg_joint
        - rh_hip_joint
        - rh_upper_leg_joint
        - rh_lower_leg_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      lf_hip_joint        : {p: 1000, d: 0.01, i: 20}
      lf_upper_leg_joint  : {p: 1000, d: 0.01, i: 20}
      lf_lower_leg_joint  : {p: 1000, d: 0.01, i: 20}
      rf_hip_joint        : {p: 1000, d: 0.01, i: 20}
      rf_upper_leg_joint  : {p: 1000, d: 0.01, i: 20}
      rf_lower_leg_joint  : {p: 1000, d: 0.01, i: 20}
      lh_hip_joint        : {p: 1000, d: 0.01, i: 20}
      lh_upper_leg_joint  : {p: 1000, d: 0.01, i: 20}
      lh_lower_leg_joint  : {p: 1000, d: 0.01, i: 20}
      rh_hip_joint        : {p: 1000, d: 0.01, i: 20}
      rh_upper_leg_joint  : {p: 1000, d: 0.01, i: 20}
      rh_lower_leg_joint  : {p: 1000, d: 0.01, i: 20}  
      