teleop_node:
  ros__parameters:
    
    turn_calc_w: 0.75
    turn_calc_l: 0.75

    #The teleop node must find axis_linear and axis_angular
    #Other axis are optional
    axis_map: [
                "axis_vx: 1", # L STICK X
                "axis_vy: 0", # L STICK X
                "axis_wz: 3", # R STICK Y
                "axis_turn_left: 4", # NA
                "axis_turn_right: 5" # NA
    ]

    # The teleop node will work without buttons.
    #
    button_map: [
                  # increase and decrease gain
                  "button_less_gain: 12", # LB, NA
                  "button_more_gain: 10", # RB, NA
                  
                  # function button
                  "button_function: 2", # Confirm

                  # the teleop lock will publish true on the teleop lock topic
                  # [button_function + button_teleop_lock] to unlock
                  "button_teleop_lock: 9", # BACK
                  "button_inverter: 3", # BACK

                  # Switch drive mode
                  "button_left: 7", # Mode Switch Left
                  "button_forward: 8", # Mode Switch Right

                  # Pivot on the spot buttons
                  "button_turn_left: 4",  # Pivot Switch Left   -> Set to -1 to use axis values!!!
                  "button_turn_right: 6", # Pivot Switch Right  -> Set to -1 to use axis values!!!

                  # Other buttons
                  "button_0: 0", # Speed
                  "button_1: 1", # Generic
                  "button_2: 11", # NA
                  "button_3: 3", # Potato
                  "button_4: 15", # NA
                  "button_5: 5", # Pivot Switch Centre
                  "button_6: 16", # NA
                  "button_7: 13", # NA
                  "button_8: 14" # NA
    ]


    # Button that must be pressed when turning in place
    button_turning_safety: button_function


    # Button combination for homing
    # Buttons must be pressed at the same time
    home_buttons: [button_function, button_3]


    # Button combination for changing to omni mode
    # Buttons must be pressed at the same time
    omni_buttons: [button_6, button_2] # NA


    # Button combination for increasing or decreasing
    # gains
    kv_default_buttons: [button_less_gain, button_more_gain] # NA
    speed_up_buttons: [button_0, button_3]
    speed_down_buttons: [button_0]


    #  Button combinations for setting the orientation
    mode_left_buttons: [button_left]
    mode_forward_buttons: [button_forward]


    # The teleop node can call an arb. number of user-specified (std_srv::Trigger) services
    # button_function + <user_spec_button>
    # This will only work if button_function is defined
    # empty service names are ignored
    trigger_map: [  "button_0:void",
                    "button_1:void",
                    "button_2:relative/path/to/service",
                    "button_3:",
                    "button_4:/absolute/path/to/service",
                    "button_5:",
                    "button_6:release_esd_lock"
    ]

    gains:      [
                  "kv_default: 0.25", 
                  "kv_min: 0.1",
                  "kv_max: 1.5",
                  "kv_increment: 0.1"
    ]

    # other
    # axis_1: 0, # L STICK Y
    # axis_2: 4, # R STICK X
    # axis_3: 6, # LEFT-RIGHT
    # axis_4: 7 # UP-DOWN
